source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target ‘q’ do
    pod 'Alamofire', '~> 4.0.1'
    pod 'SwiftyJSON'
    pod 'AlamofireImage', '~> 3.0.0'
    pod 'SQLite.swift', '~> 0.11.2'
end